Fix typos in ranking-notes.md
twitter/communitynotes pull request #99
Opened 2023-05-08 19:04 UTC by dirkphilip

I noticed some typos while reading ranking-notes.md.

This pull-request corrects these typos.

2023-05-08 19:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twitter/communitynotes?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twitter/communitynotes?pullRequest=99) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twitter/communitynotes?pullRequest=99) it.</sub>

2023-05-10 03:01 UTC, jbaxter reviewed
Thanks for going through this!

2023-05-10 03:01 UTC, jbaxter commented on documentation/under-the-hood/ranking-notes.md
> +When rating notes, contributors answer the question “Is this note helpful?” Answers to that question are then used to rank notes. When Community Notes (formerly called Birdwatch) launched in January
I think this comma you added is unnecessary. Also it seems that we are actually missing a period after "Is this note helpful?"?

2023-05-10 03:01 UTC, jbaxter commented on documentation/under-the-hood/ranking-notes.md
> +The main technique we use to determine which notes are helpful or unhelpful is matrix factorization on the note-rater matrix, a sparse matrix that encodes, for each note and rater, whether that rater
Both versions seem correct here, we can default to leave it as-is

2023-05-10 03:01 UTC, jbaxter commented on documentation/under-the-hood/ranking-notes.md
> -- We are able to include somewhat helpful ratings naturally as 0.5s
Seems fine before?

2023-05-10 03:01 UTC, jbaxter commented on documentation/under-the-hood/ranking-notes.md
> +While the matrix factorization approach above has many nice properties, it doesn't give us a natural built-in way to estimate the uncertainty of its parameters. One approach that we use to help quant
happy to switch max and min but maybe also for maximum and minimum too?

2023-05-10 03:01 UTC, jbaxter commented on documentation/under-the-hood/ranking-notes.md
> +$$ a_{un} = \frac{\mathbb{1}_{a_{un}}}{ 1 + \left( {{||f_u - f_n||} \over {\tilde{f}}} \right)^5 } $$
Let's just leave the latex alone

2023-05-10 03:01 UTC, jbaxter commented on documentation/under-the-hood/ranking-notes.md
> +- Ratings, where the rater factor and note factor are equal, will achieve the maximum weight of 1.0, ratings at a 40th percentile distance will achieve a weight of 0.5, and reviews at 2x the 40th per
This was better before in my opinion

2023-05-10 03:01 UTC, jbaxter commented on documentation/under-the-hood/ranking-notes.md
> +We currently run three note-ranking models:
unnecessary

2023-05-10 03:01 UTC, jbaxter requested changes
Thanks for going through this!

2023-05-10 10:04 UTC, dirkphilip commented on documentation/under-the-hood/ranking-notes.md
> +We currently run three note-ranking models:
Ok, I removed this

2023-05-10 10:05 UTC, dirkphilip commented on documentation/under-the-hood/ranking-notes.md
> +- Ratings, where the rater factor and note factor are equal, will achieve the maximum weight of 1.0, ratings at a 40th percentile distance will achieve a weight of 0.5, and reviews at 2x the 40th per
I think should still be "a tag" rather than "an tag". But I think leaving the comma's out is fine.

2023-05-10 10:05 UTC, dirkphilip commented on documentation/under-the-hood/ranking-notes.md
> +$$ a_{un} = \frac{\mathbb{1}_{a_{un}}}{ 1 + \left( {{||f_u - f_n||} \over {\tilde{f}}} \right)^5 } $$
Sure

2023-05-10 10:05 UTC, dirkphilip commented on documentation/under-the-hood/ranking-notes.md
> +While the matrix factorization approach above has many nice properties, it doesn't give us a natural built-in way to estimate the uncertainty of its parameters. One approach that we use to help quant
Made the change.

2023-05-10 10:10 UTC, dirkphilip commented on documentation/under-the-hood/ranking-notes.md
> -- We are able to include somewhat helpful ratings naturally as 0.5s
I guess I misunderstood this line. I read it as "0.5 s", while I think it was meant to be understood as "zero point fives" or "halfs".

I suggest changing this to:
> We are able to include somewhat helpful ratings naturally by using a value of 0.5
to make this unambiguous.

2023-05-10 10:11 UTC, dirkphilip commented on documentation/under-the-hood/ranking-notes.md
> +The main technique we use to determine which notes are helpful or unhelpful is matrix factorization on the note-rater matrix, a sparse matrix that encodes, for each note and rater, whether that rater
Sure

2023-05-10 10:12 UTC, dirkphilip commented on documentation/under-the-hood/ranking-notes.md
> +When rating notes, contributors answer the question “Is this note helpful?” Answers to that question are then used to rank notes. When Community Notes (formerly called Birdwatch) launched in January
Sure, and fixed the missing period in the next commit

2023-12-19 23:52 UTC, closed without merging